### ISSUE TITLE
Code advice

### ISSUE THREAD

**Issue by JieWu02** [zichongc/DoesFS#1]
Thanks for your work, all the tests are working fine with inference, generation etc, but 24GB gpu memory is not enough for training with batch size 4 for example. When I reduce the batch size to 2, 24GB memory still cuda out of memory with training, I guess if there is any memory accumulation problem in the code or not, thanks for your time!

**Comment by zichongc** [comment]
Hi, thank you for your interest in our work. 
We tested the training code again in our local environment (24GB gpu) and it worked fine! :)

**Comment by JieWu02** [comment]
Thanks for your patience，I will check the environment and make more tries

Bests，
